# openapi2-run.yaml
swagger: '2.0'
info:
  title: fahagc-backend This is a specification for fahagc API.
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://firebase-auth-hosting-api-gateway-cloudrun-4lvq7hntvq-an.a.run.app

# Configurations for the API authorization
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # Replace YOUR-PROJECT-ID with your project ID
    x-google-issuer: "https://securetoken.google.com/fahagc-c908b"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "fahagc-c908b"

paths:
  /greeting_message:
    get:
      summary: Cloud run greeting
      operationId: greeting_message
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /special_message:
    get:
      summary: The special message from cloud run
      operationId: special_message
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - firebase: [ ]